version: "3.9"
services:
  postgres:
        image: postgres:10.5
        container_name: postgresDb
        restart: always
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
          - '5432:5432'